-- ============================================================
-- Migration 006 — Approval queue + Context Trail + Soul.
--
-- This is the thesis-change migration: every actionable item can carry a
-- proposed_action (an executable artifact the user approves) and a
-- source_excerpt (the raw underlying content, for the Context Trail tab).
-- Soul lives on the users table as a learned communication-style profile
-- the agent uses when drafting on the user's behalf.
-- ============================================================

-- ─── items: proposed action + source excerpt ──────────────────────────
--
-- proposed_action is the artifact the user is approving. Examples:
--   { "kind": "gmail_compose",
--     "to":   ["jacob@example.com"],
--     "subject": "Re: Previous meetings - Pending deals",
--     "body": "Hi Jacob, ...",
--     "in_reply_to_message_id": "..." }
--
-- source_excerpt is the raw underlying content the agent drew on (email
-- thread body, meeting transcript snippet, Slack message). Used by the
-- Context Trail tab so users can audit why the agent decided to draft this.

alter table public.items
  add column if not exists proposed_action jsonb,
  add column if not exists source_excerpt text;

-- Helpful when the UI filters for "has draft to approve".
create index if not exists idx_items_has_proposed_action
  on public.items ((proposed_action is not null))
  where proposed_action is not null;

-- ─── users: communication style (Soul) ────────────────────────────────
--
-- Long markdown blob describing how the user writes. Generated by
-- scripts/analyze-soul.ts from the user's last ~50 sent emails.
-- Used as the system prompt when the agent drafts replies on the user's
-- behalf.

alter table public.users
  add column if not exists communication_style text;
